### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by xmoufyy** [PerimeterX/restringer#84]
here il give you the log
[+] Obfuscation type is Generic
[-] Error on loop #0: TypeError: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at getAllScopes (C:\Users\moufy\node_modules\flast\src\flast.js:225:36)
    at generateFlatAST (C:\Users\moufy\node_modules\flast\src\flast.js:76:18)
    at new Arborist (C:\Users\moufy\node_modules\flast\src\arborist.js:17:15)
    at runLoop (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\modules\utils\runLoop.js:29:18)
    at REstringer._loopSafeAndUnsafeDeobfuscationMethods (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:155:13)
    at REstringer.deobfuscate (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:177:8)
    at Object.<anonymous> (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:215:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
[-] Error on loop #0: TypeError: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at getAllScopes (C:\Users\moufy\node_modules\flast\src\flast.js:225:36)
    at generateFlatAST (C:\Users\moufy\node_modules\flast\src\flast.js:76:18)
    at new Arborist (C:\Users\moufy\node_modules\flast\src\arborist.js:17:15)
    at runLoop (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\modules\utils\runLoop.js:29:18)
    at REstringer._loopSafeAndUnsafeDeobfuscationMethods (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:156:13)
    at REstringer.deobfuscate (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:177:8)
    at Object.<anonymous> (C:\Users\moufy\Desktop\yeah\restringer-1.9.0\src\restringer.js:215:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
[-] Nothing was deobfuscated  ¯\_(ツ)_/¯

**Comment by xmoufyy** [comment]
i can share the input code and the output code privately if you want

**Comment by BenBaryoPX** [comment]
See closing comment on #83
